CREATE DATABASE LEADCRM_DB
GO

USE LEADCRM_DB
GO


CREATE TABLE CUSTOMER (
    CUSTOMERID INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    EMAIL VARCHAR(30),
    CONTACT_NUMBER VARCHAR(30),
    PREFERENCES VARCHAR(50)
)
GO


CREATE TABLE PRODUCT_LINE (
    PRODUCTID INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(225) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(225) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(225) NOT NULL,
    PRODUCT_PRICE MONEY
)
GO


CREATE TABLE MARKETING_CAMPAIGN (
    CAMPAIGNID INT IDENTITY(1,1) PRIMARY KEY,
    CAMPAIGN_NAME VARCHAR(100) NOT NULL,
    CAMPAIGN_TYPE VARCHAR(50) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    BUDGET DECIMAL(10,2) NOT NULL
)
GO


CREATE TABLE LEADS (
    LEADID INT PRIMARY KEY,
    LEADSOURCE VARCHAR(50),
    LEADSTATUS VARCHAR(50),
    DATEGENERATED DATE,
    CUSTOMERID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMERID)
)
GO


CREATE TABLE CUSTOMER_CAMPAIGN (
    CUSTOMER_CAMPAIGN_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMERID INT NOT NULL,
    CAMPAIGNID INT NOT NULL,
    RESPONSE_STATUS VARCHAR(50),

    FOREIGN KEY (CUSTOMERID)
        REFERENCES CUSTOMER(CUSTOMERID),

    FOREIGN KEY (CAMPAIGNID)
        REFERENCES MARKETING_CAMPAIGN(CAMPAIGNID)
)
GO


CREATE TABLE SERVICE_OFFERING (
    SERVICEID INT IDENTITY(1,1) PRIMARY KEY,
    SERVICE_NAME VARCHAR(255) NOT NULL,
    SERVICE_TYPE VARCHAR(255) NOT NULL,
    SERVICE_CATEGORY VARCHAR(255) NOT NULL,
    SERVICE_PRICE DECIMAL(10,2) NOT NULL,
    SERVICE_STATUS VARCHAR(255) DEFAULT 'Available'
)
GO


CREATE TABLE CUSTOMER_SERVICE_SUPP (
    CUSTOMER_SERVICE_SUPP_ID INT IDENTITY(1,1) PRIMARY KEY,
    SERVICE_TYPE VARCHAR(50),
    ISSUE_DESCRIPTION VARCHAR(30),
    CUSTOMERID INT NOT NULL,
    SERVICEID INT NOT NULL,

    FOREIGN KEY (CUSTOMERID)
        REFERENCES CUSTOMER(CUSTOMERID),

    FOREIGN KEY (SERVICEID)
        REFERENCES SERVICE_OFFERING(SERVICEID)
)
GO


CREATE TABLE SALESFORCE_AUTOMATION (
    SALESID INT PRIMARY KEY,
    CUSTOMERID INT NOT NULL,
    PRODUCTID INT NOT NULL,
    OPPORTUNITY_STAGE VARCHAR(50),
    EXPECTED_REVENUE DECIMAL(10,2),
    CLOSING_DATE DATE,

    FOREIGN KEY (CUSTOMERID)
        REFERENCES CUSTOMER(CUSTOMERID),

    FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT_LINE(PRODUCTID)
)
GO