USE LEADCRM_DB;
GO

SELECT *
FROM CUSTOMER;

SELECT *
FROM LEADS;

SELECT *
FROM PRODUCT_LINE;

SELECT *
FROM MARKETING_CAMPAIGN;

SELECT *
FROM CUSTOMER_CAMPAIGN;

SELECT *
FROM SERVICE_OFFERING;

SELECT *
FROM CUSTOMER_SERVICE_SUPP;

SELECT *
FROM SALESFORCE_AUTOMATION;

SELECT
    C.CUSTOMERID,
    C.FIRST_NAME AS CUSTOMER_NAME,
    C.EMAIL,
    C.CONTACT_NUMBER,
    P.PRODUCT_NAME AS PRODUCT_PURCHASED,
    P.PRODUCT_CATEGORY,
    P.PRODUCT_PRICE,
    S.OPPORTUNITY_STAGE,
    S.EXPECTED_REVENUE,
    S.CLOSING_DATE,
    L.LEADSOURCE,
    L.LEADSTATUS,
    L.DATEGENERATED
FROM CUSTOMER C
LEFT JOIN SALESFORCE_AUTOMATION S
    ON C.CUSTOMERID = S.CUSTOMERID
LEFT JOIN PRODUCT_LINE P
    ON S.PRODUCTID = P.PRODUCTID
LEFT JOIN LEADS L
    ON C.CUSTOMERID = L.CUSTOMERID
ORDER BY C.CUSTOMERID;

SELECT
    C.FIRST_NAME AS CUSTOMER,
    C.EMAIL,
    P.PRODUCT_NAME AS ITEM,
    P.PRODUCT_PRICE AS PRICE,
    S.EXPECTED_REVENUE AS EXPECTED_REVENUE,
    S.OPPORTUNITY_STAGE AS STATUS,
    S.CLOSING_DATE AS EXPECTED_CLOSING_DATE
FROM CUSTOMER C
INNER JOIN SALESFORCE_AUTOMATION S
    ON C.CUSTOMERID = S.CUSTOMERID
INNER JOIN PRODUCT_LINE P
    ON S.PRODUCTID = P.PRODUCTID
WHERE C.CUSTOMERID = 1;

SELECT
    C.FIRST_NAME AS CUSTOMER,
    C.EMAIL,
    P.PRODUCT_NAME AS ITEM,
    P.PRODUCT_PRICE AS PRICE,
    S.EXPECTED_REVENUE AS EXPECTED_REVENUE,
    S.OPPORTUNITY_STAGE AS STATUS,
    S.CLOSING_DATE AS EXPECTED_CLOSING_DATE
FROM CUSTOMER C
INNER JOIN SALESFORCE_AUTOMATION S
    ON C.CUSTOMERID = S.CUSTOMERID
INNER JOIN PRODUCT_LINE P
    ON S.PRODUCTID = P.PRODUCTID
WHERE C.CUSTOMERID = 2;

SELECT
    C.FIRST_NAME AS CUSTOMER,
    C.EMAIL,
    P.PRODUCT_NAME AS ITEM,
    P.PRODUCT_PRICE AS PRICE,
    S.EXPECTED_REVENUE AS EXPECTED_REVENUE,
    S.OPPORTUNITY_STAGE AS STATUS,
    S.CLOSING_DATE AS EXPECTED_CLOSING_DATE
FROM CUSTOMER C
INNER JOIN SALESFORCE_AUTOMATION S
    ON C.CUSTOMERID = S.CUSTOMERID
INNER JOIN PRODUCT_LINE P
    ON S.PRODUCTID = P.PRODUCTID
WHERE C.CUSTOMERID = 3;